[package]
name = "liquid_code_gen"
edition = "2018"
version = "0.2.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
build = "build.rs"

[lib]
proc-macro = true

[workspace]
members = [
    ".",
    "liquidlib",
]
